### ISSUE TITLE
Crash when trying to upload a file with an angle bracket in the file name

### ISSUE THREAD

**Issue by kirbyfan64** [skilion/onedrive#224]
```
ryan@DevPC-LX2 ~ $ onedrive
Uploading: ./android/aots2/13 - YAMANAIAME <FMv>.flac.ogg
std.json.JSONException@std/json.d(1393): Unexpected character '<'. (Line 1:1)
<!DOCTYPE html>
<html>
    <head>
        <title>A potentially dangerous Request.RawUrl value was detected from the client (=&quot;...AMANAIAME &lt;FMv&gt;.flac.ogg:/crea...&quot;).</title>
        <meta name="viewport" content="width=device-width" />
        <style>
         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} 
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }
         @media screen and (max-width: 639px) {
          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
         }
         @media screen and (max-width: 479px) {
          pre { width: 280px; }
         }
        </style>
    </head>

    <body bgcolor="white">

            <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>

            <h2> <i>A potentially dangerous Request.RawUrl value was detected from the client (=&quot;...AMANAIAME &lt;FMv&gt;.flac.ogg:/crea...&quot;).</i> </h2></span>

            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

            <b> Description: </b>ASP.NET has detected data in the request that is potentially dangerous because it might include HTML markup or script. The data might represent an attempt to compromise the security of your application, such as a cross-site scripting attack. If this type of input is appropriate in your application, you can include code in a web page to explicitly allow it. For more information, see http://go.microsoft.com/fwlink/?LinkID=212874.
            <br><br>

            <b> Exception Details: </b>System.Web.HttpRequestValidationException: A potentially dangerous Request.RawUrl value was detected from the client (=&quot;...AMANAIAME &lt;FMv&gt;.flac.ogg:/crea...&quot;).<br><br>

            <b>Source Error:</b> <br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code>

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.</code>

                  </td>
               </tr>
            </table>

            <br>

            <b>Stack Trace:</b> <br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

[HttpRequestValidationException (0x80004005): A potentially dangerous Request.RawUrl value was detected from the client (=&quot;...AMANAIAME &lt;FMv&gt;.flac.ogg:/crea...&quot;).]
   System.Web.HttpRequest.ValidateString(String value, String collectionKey, RequestValidationSource requestCollection) +12364126
   System.Web.HttpRequest.get_RawUrl() +133
   Microsoft.Online.AggregatorService.WebService.ContextHelper.GetIncomingUrlTraceParameter(HttpContextBase httpContext) in e:\bt\837629\repo\src\dev\WebService\ContextHelper.cs:211
   Microsoft.Online.AggregatorService.WebService.AuthenticationModule.InitializeAndGetLogContext(HttpContextWrapper currentContextWrapper) in e:\bt\837629\repo\src\dev\WebService\AuthenticationModule.cs:299
   Microsoft.Online.AggregatorService.WebService.AuthenticationModule.Context_BeginRequest(Object sender, EventArgs e) in e:\bt\837629\repo\src\dev\WebService\AuthenticationModule.cs:107
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +92
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously) +165
</pre></code>

                  </td>
               </tr>
            </table>

            <br>

            <hr width=100% size=1 color=silver>

            <b>Version Information:</b>&nbsp;Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.36366

            </font>

    </body>
</html>
<!-- 
[HttpRequestValidationException]: A potentially dangerous Request.RawUrl value was detected from the client (=&quot;...AMANAIAME &lt;FMv&gt;.flac.ogg:/crea...&quot;).
   at System.Web.HttpRequest.ValidateString(String value, String collectionKey, RequestValidationSource requestCollection)
   at System.Web.HttpRequest.get_RawUrl()
   at Microsoft.Online.AggregatorService.WebService.ContextHelper.GetIncomingUrlTraceParameter(HttpContextBase httpContext) in e:\bt\837629\repo\src\dev\WebService\ContextHelper.cs:line 211
   at Microsoft.Online.AggregatorService.WebService.AuthenticationModule.InitializeAndGetLogContext(HttpContextWrapper currentContextWrapper) in e:\bt\837629\repo\src\dev\WebService\AuthenticationModule.cs:line 299
   at Microsoft.Online.AggregatorService.WebService.AuthenticationModule.Context_BeginRequest(Object sender, EventArgs e) in e:\bt\837629\repo\src\dev\WebService\AuthenticationModule.cs:line 107
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
--><!-- 
This error page might contain sensitive information because ASP.NET is configured to show verbose error messages using &lt;customErrors mode="Off"/&gt;. Consider using &lt;customErrors mode="On"/&gt; or &lt;customErrors mode="RemoteOnly"/&gt; in production environments.-->
----------------
??:? pure @safe void std.json.parseJSON!(char[]).parseJSON(char[], int, std.json.JSONOptions).parseValue(ref std.json.JSONValue) [0xe0cfb67b]
??:? pure @safe std.json.JSONValue std.json.parseJSON!(char[]).parseJSON(char[], int, std.json.JSONOptions) [0xe0cfa3b6]
??:? std.json.JSONValue onedrive.OneDriveApi.perform() [0xe0cf9624]
??:? std.json.JSONValue onedrive.OneDriveApi.perform(const(void)[]) [0xe0cf9253]
??:? std.json.JSONValue onedrive.OneDriveApi.post!(void).post(const(char)[], const(void)[]) [0xe0cfa17e]
??:? void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0xe0d078e8]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xe0d0714e]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xe0d06ff2]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xe0d06ff2]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xe0d06ff2]
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0xe0d05185]
??:? void main.performSync(sync.SyncEngine) [0xe0ceef00]
??:? _Dmain [0xe0cee713]
Segmentation fault (core dumped)
ryan@DevPC-LX2 ~ $ 
```

This particularly sucks because [Sawano uses track titles like that a LOT](http://vgmdb.net/album/66833)...

**Comment by Scimmia22** [comment]
The readme clearly says:

File naming

The files and directories in the synchronization directory must follow the Windows naming conventions. The application will crash for example if you have two files with the same name but different case. This is expected behavior and won't be fixed.

**Comment by kirbyfan64** [comment]
Oh, sorry! I saw that part, but I didn't realize angle brackets were disallowed according to Windows naming rules.

**Comment by cvoltz** [comment]
I understand the limitation of having to follow the Windows naming convention but I don't think the program should crash. Why not just skip the file? A service or application shouldn't ever crash/segfault/coredump. Errors should always be handled gracefully.

**Comment by thomasfedb** [comment]
@kirbyfan64 can you reproduce this with the latest commit?

**Comment by abraunegg** [comment]
@cvoltz 

> A service or application shouldn't ever crash/segfault/coredump. Errors should always be handled gracefully.

Totally agree

@kirbyfan64 

A number of changes including a fix for this has been made in #314 - can you re-try with that version?

**Comment by abraunegg** [comment]
@kirbyfan64 
Can you please provide an update or close this case
